/*CREATE TABLE USUARIO (
    ID NUMBER(6) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    ENDERECO VARCHAR2(100),
    TELEFONE VARCHAR2(15),
    EMAIL    VARCHAR2(50),
    GESTOR   VARCHAR2(1) DEFAULT 'N' NOT NULL CHECK (GESTOR IN ('S', 'N')) );


ALTER TABLE USUARIO ADD CONSTRAINT PKID_USUARIO PRIMARY KEY (ID);*/

CREATE SEQUENCE SQID_USUARIO;


    
